gitlabUrl: GITLAB_URL #https://gitlab.com?
runnerRegistrationToken: GITLAB_REGISTRATION_TOKEN #From CI section on giltab
rbac:
  create: true
runners:
  ## Run all containers with the privileged flag enabled
  ## This will allow the docker:stable-dind image to run if you need to run Docker
  ## commands. Please read the docs before turning this on:
  ## ref: https://docs.gitlab.com/runner/executors/kubernetes.html#using-docker-dind
  ##
  privileged: true
  ## Build Container specific configuration
  ##
builds:
  cpuLimit: 200m
  memoryLimit: 4096Mi
  #cpuRequests: 100m
  #memoryRequests: 128Mi

## Service Container specific configuration
##
services:
  cpuLimit: 200m
  memoryLimit: 1024Mi
  #cpuRequests: 100m
  #memoryRequests: 128Mi

## Helper Container specific configuration
##
helpers:
  cpuLimit: 200m
  memoryLimit: 1024Mi
  #cpuRequests: 100m
  #memoryRequests: 128Mi	

cache:
  ## General settings
  cacheType: s3
  cachePath: "gitlab_runner"
  cacheShared: true

  ## S3 settings
  s3ServerAddress: s3.amazonaws.com
  s3BucketName: gitlab-ci
  s3CacheInsecure: false
  secretName: s3access
	
