gitlabUrl: GITLAB_URL #https://gitlab.com?
runnerRegistrationToken: GITLAB_REGISTRATION_TOKEN #From CI section on giltab
rbac:
  create: true
runners:
  ## Run all containers with the privileged flag enabled
  ## This will allow the docker:stable-dind image to run if you need to run Docker
  ## commands. Please read the docs before turning this on:
  ## ref: https://docs.gitlab.com/runner/executors/kubernetes.html#using-docker-dind
  ##
  privileged: true
